In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
house=pd.read_csv("E://Datasets//New Dataset//house-prices.csv")
house.head(10)

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East
5     6  114600  1780         3          2       2    No        North
6     7  151600  1830         3          3       3   Yes         West
7     8  150700  2160         4          2       2    No         West
8     9  119200  2110         4          2       3    No         East
9    10  104000  1730         3          3       3    No         East

In [34]:
house.drop(columns=["Brick","Neighborhood"],axis=1,inplace=True)

In [35]:
house.columns

Index(['Home', 'Price', 'SqFt', 'Bedrooms', 'Bathrooms', 'Offers'], dtype='object')

In [41]:
#splitting data into independent and dependent variable.
x_data=house.iloc[:,2:8].values
y_data=house.iloc[:,1].values

In [43]:
x_data

array([[1790,    2,    2,    2],
       [2030,    4,    2,    3],
       [1740,    3,    2,    1],
       [1980,    3,    2,    3],
       [2130,    3,    3,    3],
       [1780,    3,    2,    2],
       [1830,    3,    3,    3],
       [2160,    4,    2,    2],
       [2110,    4,    2,    3],
       [1730,    3,    3,    3],
       [2030,    3,    2,    3],
       [1870,    2,    2,    2],
       [1910,    3,    2,    4],
       [2150,    3,    3,    5],
       [2590,    4,    3,    4],
       [1780,    4,    2,    1],
       [2190,    3,    3,    4],
       [1990,    3,    3,    4],
       [1700,    2,    2,    1],
       [1920,    3,    3,    2],
       [1790,    3,    2,    3],
       [2000,    3,    2,    4],
       [1690,    3,    2,    3],
       [1820,    3,    2,    3],
       [2210,    4,    3,    2],
       [2290,    4,    3,    3],
       [2000,    4,    2,    3],
       [1700,    3,    2,    2],
       [1600,    2,    2,    3],
       [2040,    4,    3,    1],
       [22

In [44]:
y_data

array([114300, 114200, 114800,  94700, 119800, 114600, 151600, 150700,
       119200, 104000, 132500, 123000, 102600, 126300, 176800, 145800,
       147100,  83600, 111400, 167200, 116200, 113800,  91700, 106100,
       156400, 149300, 137000,  99300,  69100, 188000, 182000, 112300,
       135000, 139600, 117800, 117100, 117500, 147000, 131300, 108200,
       106600, 133600, 105600, 154000, 166500, 103200, 129800,  90300,
       115900, 107500, 151100,  91100, 117400, 130800,  81300, 125700,
       140900, 152300, 138100, 155400, 180900, 100900, 161300, 120500,
       130300, 111100, 126200, 151900,  93600, 165600, 166700, 157600,
       107300, 125700, 144200, 106900, 129800, 176500, 121300, 143600,
       143400, 184300, 164800, 147700,  90500, 188300, 102700, 172500,
       127700,  97800, 143100, 116500, 142600, 157100, 160600, 152500,
       133300, 126800, 145500, 171000, 103200, 123100, 136800, 211200,
        82300, 146900, 108500, 134000, 117000, 108700, 111600, 114900,
      

In [47]:
#splitting data into training and testing data.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.25,random_state=0)

In [48]:
#importing library for mulitple linear regression.
from sklearn.linear_model import LinearRegression
house_lin=LinearRegression()

In [49]:
house_lin.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
x_train

array([[1930,    3,    2,    2],
       [1920,    3,    2,    1],
       [1780,    4,    2,    1],
       [2080,    3,    3,    2],
       [1970,    2,    2,    1],
       [1810,    3,    2,    3],
       [1980,    3,    2,    3],
       [2010,    3,    2,    5],
       [1830,    3,    3,    3],
       [2110,    3,    2,    2],
       [2150,    2,    3,    4],
       [2000,    2,    2,    1],
       [2220,    4,    3,    2],
       [1740,    2,    2,    2],
       [1650,    3,    2,    3],
       [2250,    4,    3,    2],
       [2070,    2,    2,    2],
       [1700,    3,    2,    2],
       [1700,    2,    2,    1],
       [2530,    4,    3,    4],
       [1870,    2,    2,    2],
       [2210,    3,    3,    4],
       [1900,    2,    2,    2],
       [1910,    2,    3,    2],
       [1520,    2,    2,    3],
       [1610,    2,    2,    2],
       [2030,    4,    2,    3],
       [2190,    3,    2,    3],
       [2130,    3,    2,    3],
       [1710,    2,    2,    1],
       [19

In [53]:
y_pred=house_lin.predict(x_test)
print(y_pred)

[110156.0523436  168094.81798263 108161.62930778 100890.21327165
 135327.56717923 130908.25068122 133160.42008108 159074.52360056
 148059.5137369  152478.83023491 172095.86572843 120925.51751737
  96257.29373567 150317.63775096 156576.80951081 153827.59611699
 130817.27376531 162119.08717877 125306.93774927 128442.47824339
  99644.33353387 119764.66008131 122422.89655923 113788.92927745
 127152.74762531 141451.91114286 142458.20080495 129404.91702517
 137456.81801126 115918.18010949 112879.57114547 150563.18244085]


In [54]:
#Calculating accuracy of model.
from sklearn.metrics import r2_score
result=r2_score(y_test,y_pred)

In [55]:
print(result)

0.5921796242692079
